# Site settings
title: Sai Tej Paruchuri
description: Research Scientist in Plasma Control and Nonlinear Systems
url: "https://saitejp.github.io"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Education
    url: /education
  - title: Experience
    url: /experience
  - title: Research
    url: /research
  - title: Publications
    url: /publications
  - title: Teaching
    url: /teaching
  - title: Service
    url: /service
  - title: CV
    url: /assets/pdf/CV_ParuchuriST.pdf

# Theme settings
# Current theme: minimal (clean, simple, content-focused)
theme: jekyll-theme-minimal

# Recommended academic themes (uncomment one to use):
# theme: jekyll-theme-slate      # Professional with dark header, excellent readability
# theme: jekyll-theme-cayman     # Clean design with prominent header, good for highlighting research areas
# remote_theme: mmistakes/minimal-mistakes  # Feature-rich academic theme, requires additional setup

# For minimal theme, you can customize the logo and sidebar
# logo: /assets/img/logo.png  # Add a profile photo or logo
show_downloads: false       # Set to true if you want to highlight CV/resume downloads

# Social links
# github_username: saitejp
linkedin_username: saitejparuchuri
google_scholar: rxMB0HAAAAAJ
